import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert' as convert;
import 'package:shagher/packages/pages/api/handle_api.dart';
import 'package:shagher/packages/pages/api/path_api.dart';
import 'package:shagher/packages/pages/company/models/model_company/auto_generated_company.dart';
import 'package:shagher/packages/pages/company/models/model_company/list_company.dart';
import 'package:shagher/packages/pages/user/models/root_user.dart';
import 'package:shagher/service/lang/app_lang.dart';

class ApiController extends HandelApi {
  final int _timeOut = 100;

  // * get company App Data
  @override
  Future<ModelListCompany?> getCompany(BuildContext context) async {
    try {
      // * URL
      Uri _uri = Uri.parse(
          PathApi.baseApi + AppLang.currentLang(context) + PathApi.company);

      late ModelListCompany _data;

      http.Response _req =
          await http.get(_uri).timeout(Duration(seconds: _timeOut));
      if (_req.statusCode == 200) {
        var _dataJson = convert.jsonDecode(_req.body);
        _data = ModelListCompany.fromJson(json: _dataJson);
      } else {
        throw Exception('Failed To Fetch Data');
      }
      return _data;
    } catch (e) {
      // print(error);
    }
  }

  // * get company app
  @override
  Future<ModelRootUser?> getUser(BuildContext context) async {
    // * URL
    Uri _uri = Uri.parse(
        PathApi.baseApi + AppLang.currentLang(context) + PathApi.company);

    late ModelRootUser _datacompany;
    return http.get(_uri).timeout(Duration(seconds: _timeOut)).then(
      (response) {
        if (response.statusCode == 200) {
          var _json = convert.jsonDecode(response.body);
          return _datacompany = ModelRootUser.fromJson(json: _json);
        } else {
          throw Exception('Failed To Fetch Data');
        }
      },
    ).onError((error, stackTrace) {
      //print("error : $error");
      return _datacompany;
    });
  }

  // * app company By Id
  @override
  Future<AutogeneratedCompany?> getAppById(BuildContext context,
      {required String id}) {
    // * URL
    Uri _uri = Uri.parse(PathApi.baseApi +
        AppLang.currentLang(context) +
        PathApi.company +
        '/$id');

    late AutogeneratedCompany _datacompany;
    return http.get(_uri).timeout(Duration(seconds: _timeOut)).then(
      (response) {
        if (response.statusCode == 200) {
          var _json = convert.jsonDecode(response.body);
          return _datacompany = AutogeneratedCompany.fromJson(json: _json);
        } else {
          throw Exception('Failed To Fetch Data');
        }
      },
    ).onError((error, stackTrace) {
      // print("error : $error");
      return _datacompany;
    });
  }
}
