import 'package:flutter/material.dart';
import 'package:shagher/packages/pages/company/models/model_company/auto_generated_company.dart';
import 'package:shagher/packages/pages/company/models/model_company/list_company.dart';
import 'package:shagher/packages/pages/user/models/root_user.dart';

abstract class HandelApi {
  // * get Company apps as List
  Future<ModelListCompany?> getCompany(BuildContext context);

  // * get User app as List
  Future<ModelRootUser?> getUser(BuildContext context);

  // * get App By ID
  Future<AutogeneratedCompany?> getAppById(
    BuildContext context, {
    required String id,
  });
}
